version: '3.1'
services:
  worker:
    build:
      context: .
    environment: 
      MONGO_URL: "mongodb://db:27017"
  db:
    image: mongo:4.2.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example