FROM golang:1.13

RUN go get -v golang.org/x/tools/cmd/goimports && \
    go get -v github.com/rogpeppe/godef && \
    go get -v github.com/go-delve/delve/cmd/dlv && \
    go get -v github.com/rogpeppe/godef && \
    go get -v github.com/ramya-rao-a/go-outline && \
    go get -v github.com/stamblerre/gocode && \
    go get -v github.com/uudashr/gopkgs/cmd/gopkgs